version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password.01"
    ports:
      # Port exposed   MySQL Port running inside container
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306